/*|~^~|Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 |~^~|All rights reserved.
 |~^~|
 |~^~|Redistribution and use in source and binary forms, with or without
 |~^~|modification, are permitted provided that the following conditions are met:
 |~^~|
 |~^~|-1. Redistributions of source code must retain the above copyright notice, this
 |~^~|ist of conditions and the following disclaimer.
 |~^~|
 |~^~|-2. Redistributions in binary form must reproduce the above copyright notice,
 |~^~|this list of conditions and the following disclaimer in the documentation
 |~^~|and/or other materials provided with the distribution.
 |~^~|
 |~^~|-3. Neither the name of the copyright holder nor the names of its contributors
 |~^~|may be used to endorse or promote products derived from this software without
 |~^~|specific prior written permission.
 |~^~|
 |~^~|THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 |~^~|AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 |~^~|IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 |~^~|DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 |~^~|FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 |~^~|DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 |~^~|SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 |~^~|CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 |~^~|OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 |~^~|OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\*/
/**
 *
 */
package edu.mit.ll.phinics.android.utils;

public class Intents {

	public static final String PHINICS_SUCCESSFUL_LOGIN = "PHINICS_SUCCESSFUL_LOGIN";
	public static final String PHINICS_FAILED_LOGIN = "PHINICS_FAILED_LOGIN";
	
	public static final String PHINICS_SUCCESSFUL_GET_INCIDENT_INFO = "PHINICS_SUCCESSFUL_GET_INCIDENT_INFO";
	public static final String PHINICS_SUCCESSFUL_GET_ALL_INCIDENT_INFO = "PHINICS_SUCCESSFUL_GET_ALL_INCIDENT_INFO";
	public static final String PHINICS_SUCCESSFUL_GET_ASSIGNMENT_INFO = "PHINICS_SUCCESSFUL_GET_ASSIGNMENT_INFO";
	public static final String PHINICS_SUCCESSFUL_GET_COLLABROOM_INFO = "PHINICS_SUCCESSFUL_GET_COLLABROOM_INFO";
			
	public static final String PHINICS_COLLABROOM_SWITCHED = "PHINICS_COLLABROOM_SWITCHED";
	public static final String PHINICS_INCIDENT_SWITCHED = "PHINICS_INCIDENT_SWITCHED";
	
	public static final String PHINICS_BT_CONNECT = "PHINICS_BT_CONNECT";
	public static final String PHINICS_BT_DISCONNECT = "PHINICS_BT_DISCONNECT";

	public static final String PHINICS_NEW_TASK_RECEIVED = "PHINICS_NEW_TASK_RECEIVED";
	public static final String PHINICS_NEW_ASSIGNMENT_RECEIVED = "PHINICS_NEW_ASSIGNMENT_RECEIVED";
	public static final String PHINICS_UPDATE_ASSIGNMENT_RECEIVED = "PHINICS_UPDATE_ASSIGNMENT_RECEIVED";
	public static final String PHINICS_NEW_CHAT_RECEIVED = "PHINICS_NEW_CHAT_RECEIVED";
	public static final String PHINICS_LAST_CHAT_RECEIVED = "PHINICS_LAST_CHAT_RECEIVED";
	public static final String PHINICS_NEW_TASK_RECEIVED_OVERVIEW = "PHINICS_NEW_TASK_RECEIVED_OVERVIEW";
	public static final String PHINICS_NEW_PERSONAL_HISTORY_RECEIVED = "PHINICS_NEW_PERSONAL_HISTORY_RECEIVED";
	public static final String PHINICS_NEW_FIELD_REPORT_RECEIVED = "PHINICS_NEW_FIELD_REPORT_RECEIVED";
	public static final String PHINICS_NEW_DAMAGE_REPORT_RECEIVED = "PHINICS_NEW_DAMAGE_REPORT_RECEIVED";
	public static final String PHINICS_NEW_MARKUP_RECEIVED = "PHINICS_NEW_MARKUP_RECEIVED";
	public static final String PHINICS_NEW_RESOURCE_REQUEST_RECEIVED = "PHINICS_NEW_RESOURCE_REQUEST_RECEIVED";
	public static final String PHINICS_NEW_SIMPLE_REPORT_RECEIVED = "PHINICS_NEW_SIMPLE_REPORT_RECEIVED";
	public static final String PHINICS_NEW_WEATHER_REPORT_RECEIVED = "PHINICS_NEW_WEATHER_REPORT_RECEIVED";
	public static final String PHINICS_NEW_CATAN_REQUEST_RECEIVED = "PHINICS_NEW_CATAN_REQUEST_RECEIVED";
	public static final String PHINICS_NEW_UXO_REPORT_RECEIVED = "PHINICS_NEW_UXO_REPORT_RECEIVED";
	
	public static final String PHINICS_VIEW_OVERVIEW = "PHINICS_VIEW_OVERVIEW";
	public static final String PHINICS_VIEW_SIMPLE_REPORTS_LIST = "PHINICS_VIEW_SIMPLE_REPORTS_LIST";
	public static final String PHINICS_VIEW_FIELD_REPORTS_LIST = "PHINICS_VIEW_FIELD_REPORTS_LIST";
	public static final String PHINICS_VIEW_DAMAGE_REPORTS_LIST = "PHINICS_VIEW_DAMAGE_REPORTS_LIST";
	public static final String PHINICS_VIEW_RESOURCE_REQUESTS_LIST = "PHINICS_VIEW_RESOURCE_REQUESTS_LIST";
	public static final String PHINICS_VIEW_WEATHER_REPORTS_LIST = "PHINICS_VIEW_WEATHER_REPORTS_LIST";
	public static final String PHINICS_VIEW_UXO_REPORTS_LIST = "PHINICS_VIEW_UXO_REPORTS_LIST";
	public static final String PHINICS_VIEW_CATAN_REQUESTS_LIST = "PHINICS_VIEW_CATAN_REQUESTS_LIST";
	
	public static final String PHINICS_POLLING_TASK = "PHINICS_POLLING_TASK";
	public static final String PHINICS_POLLING_TASK_ASSIGNMENTS = "PHINICS_POLLING_TASK_ASSIGNMENTS";
	public static final String PHINICS_POLLING_TASK_DAMAGE_REPORT = "PHINICS_POLLING_TASK_DAMAGE_REPORT";
	public static final String PHINICS_POLLING_TASK_FIELD_REPORT = "PHINICS_POLLING_TASK_FIELD_REPORT";
	public static final String PHINICS_POLLING_TASK_SIMPLE_REPORT = "PHINICS_POLLING_TASK_SIMPLE_REPORT";
	public static final String PHINICS_POLLING_TASK_RESOURCE_REQUEST = "PHINICS_POLLING_TASK_RESOURCE_REQUEST";
	public static final String PHINICS_POLLING_TASK_WEATHER_REPORT = "PHINICS_POLLING_TASK_WEATHER_REPORT";
	public static final String PHINICS_POLLING_TASK_CATAN_REQUEST = "PHINICS_POLLING_TASK_CATAN_REQUEST";
	public static final String PHINICS_POLLING_TASK_UXO_REPORT = "PHINICS_POLLING_TASK_UXO_REPORT";
	public static final String PHINICS_POLLING_TASK_CHAT_MESSAGES = "PHINICS_POLLING_TASK_CHAT_MESSAGES";
	public static final String PHINICS_POLLING_MARKUP_REQUEST = "PHINICS_POLLING_MARKUP_REQUEST";
	public static final String PHINICS_POLLING_WFS_LAYER = "PHINICS_POLLING_WFS_LAYER_";
	
	public static final String PHINICS_SHOW_INCIDENT_SELECT = "PHINICS_SHOW_INCIDENT_SELECT";
	public static final String PHINICS_SIMPLE_REPORT_PROGRESS = "PHINICS_SIMPLE_REPORT_PROGRESS";
	public static final String PHINICS_DAMAGE_REPORT_PROGRESS = "PHINICS_DAMAGE_REPORT_PROGRESS";
	public static final String PHINICS_CATAN_REQUEST_PROGRESS = "PHINICS_CATAN_REQUEST_PROGRESS";
	public static final String PHINICS_UXO_REPORT_PROGRESS = "PHINICS_UXO_REPORT_PROGRESS";
	public static final String PHINICS_SUCCESSFUL_GET_USER_ORGANIZATION_INFO = "PHINICS_SUCCESSFUL_GET_USER_ORGANIZATION_INFO";
	public static final String PHINICS_OPENAM_AUTH_TIMEOUT = "PHINICS_OPENAM_AUTH_TIMEOUT";
}
